version: "3.7"

services:
  front:
    container_name: front
    build: ./front
    volumes:
      - front:/front-app/
    ports:
      - 9000:80
    networks:
      - app
    depends_on:
      - mongo
  mongo:
    image: mongo
    container_name: mongodb
    volumes:
      - data:/data/db
    networks:
      - app
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
  mongo-ui:
    image: mongo-express
    container_name: mongoui
    restart: unless-stopped
    depends_on:
      - mongo
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
    ports:
      - "8081:8081"
    networks:
      - app
  back:
    container_name: back
    build: ./back
    networks:
      - app
    command: bash -c "npm start"
    ports:
      - 3000:3000
volumes:
  front:
  data:
networks:
  app:
    driver: bridge